### ISSUE TITLE
AOT compilation issue

### ISSUE THREAD

**Issue by megasharks** [numsu/angular2-debounce#4]
Dear contributors. Is it possible to fix AOT compilation error "Error encountered resolving symbol values statically"    encountered with Angular 4.0.0 and Angular cli 1.0.2.?
 Otherwise works fine. Thank you.

**Comment by turab007** [comment]
I am facing the same issue. Has anyone found the solution?

**Comment by sivabudh** [comment]
Found the same issue. Here's the full error output:

```
Angular compilation done, starting webpack bundling.
Error: Error encountered resolving symbol values statically. Calling function 'makeDecorator', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol Injectable in /Users/pac/Code/yaoms/node_modules/angular2-debounce/node_modules/@angular/core/src/di/metadata.d.ts, resolving symbol OpaqueToken in /Users/pac/Code/yaoms/node_modules/angular2-debounce/node_modules/@angular/core/src/di/opaque_token.d.ts, resolving symbol OpaqueToken in /Users/pac/Code/yaoms/node_modules/angular2-debounce/node_modules/@angular/core/src/di/opaque_token.d.ts
    at syntaxError (/Users/pac/Code/yaoms/node_modules/@angular/compiler/bundles/compiler.umd.js:1724:34)
    at simplifyInContext (/Users/pac/Code/yaoms/node_modules/@angular/compiler/@angular/compiler.es5.js:24818:17)
    at StaticReflector.simplify (/Users/pac/Code/yaoms/node_modules/@angular/compiler/@angular/compiler.es5.js:24830:7)
    at StaticReflector.annotations (/Users/pac/Code/yaoms/node_modules/@angular/compiler/@angular/compiler.es5.js:24278:38)
    at NgModuleResolver.resolve (/Users/pac/Code/yaoms/node_modules/@angular/compiler/@angular/compiler.es5.js:14694:34)
    at CompileMetadataResolver.getNgModuleMetadata (/Users/pac/Code/yaoms/node_modules/@angular/compiler/@angular/compiler.es5.js:15347:58)
    at addNgModule (/Users/pac/Code/yaoms/node_modules/@angular/compiler/bundles/compiler.umd.js:24171:58)
    at /Users/pac/Code/yaoms/node_modules/@angular/compiler/bundles/compiler.umd.js:24182:14
    at Array.forEach (native)
    at _createNgModules (/Users/pac/Code/yaoms/node_modules/@angular/compiler/@angular/compiler.es5.js:24151:8)
    at analyzeNgModules (/Users/pac/Code/yaoms/node_modules/@angular/compiler/bundles/compiler.umd.js:24056:14)
    at analyzeAndValidateNgModules (/Users/pac/Code/yaoms/node_modules/@angular/compiler/@angular/compiler.es5.js:24036:19)
    at AotCompiler.analyzeModulesAsync (/Users/pac/Code/yaoms/node_modules/@angular/compiler/bundles/compiler.umd.js:23752:46)
    at CodeGenerator.codegen (/Users/pac/Code/yaoms/packages/compiler-cli/src/codegen.ts:41:10)
    at /Users/pac/Code/yaoms/node_modules/src/main.ts:19:84
    at Object.main (/Users/pac/Code/tools/@angular/tsc-wrapped/src/main.ts:125:12)
    at Object.runInternal (/Users/pac/Code/yaoms/node_modules/src/main.ts:24:10)
    at /Users/pac/Code/yaoms/node_modules/src/plugin.ts:64:21
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:169:7)
    at Function.Module.runMain (module.js:607:11)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
```

Mine is Angular 4.2.5 + AOT with Webpack 3.1.

**Comment by diego-rangel** [comment]
Same issue here.

**Comment by ghost** [comment]
If you create a standard directive code in /src/debounce.directive.ts and then import and declare in app.module.ts this will work with AOT with no issues.
